### ISSUE TITLE
[Feature Request]: Implement multiple layouts 

### ISSUE THREAD

**Issue by Kaarti22** [bsoc-bitbyte/BSoC-Website#100]
### Is your feature request related to a problem? Please describe.

In the present code, each page has several components that are being imported repeatedly. If 2-3 pages has the same thing to display, then why should we import it every time. If you have some data which takes some time to get displayed in a page, and the same thing is also displayed in many other pages, imagine how much time it takes and how slow it becomes.

### Describe the solution you'd like

Implement multiple layout system. Create multiple views and make the view called only once even though it has to be showed multiple times.

**Comment by Vaibhavsahu2810** [comment]
@Kaarti22 i would like to work on this issue.I will create the view.vue file in which i will import the things which are common like navbar etc and use this page as a base layout for other pages.

**Comment by tanishkaa08** [comment]
I would like to work on this issue. I'll try to make two different layouts and use vue router to define the routes which will specify the routes for each layout .

**Comment by Kaarti22** [comment]
You could proceed now...

**Comment by tanishkaa08** [comment]
@Kaarti22 I created 3 different layouts and changed index.js file in the router section accordingly. I could only spot the navbar being displayed in most of the files, please take a look and suggest what more should I add in the layouts.
