### ISSUE TITLE
[Feature Request]: Handle responsiveness of the present landing page

### ISSUE THREAD

**Issue by Kaarti22** [bsoc-bitbyte/BSoC-Website#101]
### Is your feature request related to a problem? Please describe.

The present landing page when viewed in a laptop keeping it's width by half, it looks left aligned. When a user minimizes the website for some cause, it gives him an ugly look.
![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/129477209/2355c1ca-3cfa-40c4-ae50-ab97bde21a7a)

### Describe the solution you'd like

Handle the landing page correctly by analyzing the width of the screens.

**Comment by Vaibhavsahu2810** [comment]
@Kaarti22 i would like to work on this issue.I will update the responsiveness of the page.

**Comment by Kaarti22** [comment]
you could proceed now
