### ISSUE TITLE
[Feature Request]: Theme and assets change of the BSoC website

### ISSUE THREAD

**Issue by Kaarti22** [bsoc-bitbyte/BSoC-Website#108]
### Is your feature request related to a problem? Please describe.

The present theme of BSoC website is lacking attraction to the users due to which there's now a need of change of theme and assets of the website.

### Describe the solution you'd like

1) Update the fonts and color themes as suggested in the below pictures. 
2) Update the about view in the given manner. No need of the search icon in the about view.
3) Add a benefits view as suggested.
4) Update the colors of the search bar.
5) Add a responsive footer.
6) In the remaining pages, change the theme similar to these colors. These pictures are just for reference. 

![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/129477209/09ba5880-3d00-45bc-af70-2ffad73cab67)
![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/129477209/0f9bd2ae-a776-4bd9-a321-1c498ecc8fee)
![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/129477209/4e76cb68-08e9-4f64-94d0-9803b31e2304)
![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/129477209/ae845f6b-e4e2-428f-a3cd-0239b4cb5867)
![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/129477209/49f22679-3439-4eb4-bc5e-94e2751a2036)
![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/129477209/a49353ca-78aa-4bfa-b942-45c6626bae7b)

**Comment by ANIRUDHNARANG0** [comment]
@Kaarti22  i want to work on this issue

**Comment by kartik-grg** [comment]
@Kaarti22 I want to work on this issue, i will be creating components for navbar and footer and update the theme of the website with the help of css

**Comment by kartik-grg** [comment]
@Kaarti22, @ramG-reddy I have updated the theme of BSoC website, added the responsive footer and removed unnecessary files from assets, please review the changes.
