### ISSUE TITLE
[Feature Request]:  Make Navbar Responsive for Mobile Dispalys

### ISSUE THREAD

**Issue by Priyansh61** [bsoc-bitbyte/BSoC-Website#33]
### Is your feature request related to a problem? Please describe.

The navbar section in the site is not at all optimized for mobile version,  so we need to find a way which makes it compatible for mobile displays.

![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/96513964/5b0c3f44-8953-44f6-8344-c4d416078d1a)

### Describe the solution you'd like

We can have a side navbar for mobile displays which opens on adding a button near to the bsoc logo in the top left and in the sidebar we can add all the options

### Describe alternatives you've considered

Similar to the sidebar we can also have navar as other sites, like clicking somewhere on the navbaar completely covers the display and we can then browse through different sections.

### Developer Help

The file for the navbar component is present in` src > components > Nav.vue`

**Comment by abansal15** [comment]
pls assign this issue to me

**Comment by abansal15** [comment]
@Priyansh61  working

**Comment by abansal15** [comment]
@Priyansh61 can you please provide some more resources for doing this issue

**Comment by abansal15** [comment]
and @Priyansh61 is this project using Bootstrap?

**Comment by abansal15** [comment]
@Priyansh61 I am facing an issue in which the hamburger is working only one time means when I click the hamburger a second time it doesn't collapse can you please help

**Comment by prernadabi23** [comment]
> and @Priyansh61 is this project using Bootstrap?

Yes, you can use Bootstrap.


> @Priyansh61 I am facing an issue in which the hamburger is working only one time means when I click the hamburger a second time it doesn't collapse can you please help

To enhance your code, you can add a close button. However, there is nothing wrong with your current code.



> @Priyansh61 can you please provide some more resources for doing this issue

I recommend watching tutorial videos on YouTube to learn about creating a responsive navbar. You can find many helpful resources by searching for "responsive navbar tutorial" on YouTube.

@abansal15

**Comment by Priyansh61** [comment]
Thanks @prernadabi23 for replying on behalf. Any other help needed @abansal15 ?

**Comment by abansal15** [comment]
@Priyansh61 no trying my best

**Comment by Priyansh61** [comment]
Please raise the PR asapp

**Comment by abansal15** [comment]
@Priyansh61 can you pls check I have raised the pr on my side  ? I have to raise it again?

**Comment by Priyansh61** [comment]
@abansal15 Will check it tomorrow

**Comment by Priyansh61** [comment]
@abansal15 Please provide an expected date for the PR? Or you can checkout someother issue and let someoone else work on this.

**Comment by abansal15** [comment]
> @abansal15 Please provide an expected date for the PR? Or you can checkout someother issue and let someoone else work on this.

@Priyansh61 Raised the pr

**Comment by abansal15** [comment]
@Priyansh61 is there any more bug in it?

**Comment by Priyansh61** [comment]
@abansal15 I have left comments on the PR
