### ISSUE TITLE
[BUG]: The BSoC image on sites loads very late

### ISSUE THREAD

**Issue by Priyansh61** [bsoc-bitbyte/BSoC-Website#35]
### Describe the bug

When you go the site, you will see that the bsoc image renders very late, which is not good.

### Steps To Reproduce

- Go to https://bitbytesummerofcode.netlify.app/home
- And check how late the image appears in the logo

### Expected Behavior

The image should render instanly when the site loads, this can be fixed by compressing the size of the image used in the assets.

### Screenshots/Videos

https://bitbytesummerofcode.netlify.app/home

**Comment by anshikkay** [comment]
@Priyansh61
please assign me this issue , I would like to work

**Comment by Priyansh61** [comment]
Assigned you @anshikkay 

Pro TIp : Just use the asset image, use an online compression tool to compress it, use the new image and make a new PR that's the work done.

**Comment by Priyansh61** [comment]
Closed as completed

**Comment by anshikkay** [comment]
@Priyansh61 please assign its difficulty level

**Comment by Priyansh61** [comment]
@anshikkay I have already assigned the easy difficulty to the PR.
