### ISSUE TITLE
[Feature Request]: Delete Option to remove a PR done by Mistake

### ISSUE THREAD

**Issue by Priyansh61** [bsoc-bitbyte/BSoC-Website#46]
### Is your feature request related to a problem? Please describe.

If someone mistakenly uploads a PR, which may have some wrong information there is no way to delete the PR.

### Describe the solution you'd like

On the MyPR section, there should be a button to delete the PR with complete functioning, such that it deletes the PR from there and also subtracts the PR score from the total score.

**Comment by anshikkay** [comment]
@Priyansh61 is this issue involves backend part or just we have to make button for delete option.
thank you!!

**Comment by Priyansh61** [comment]
Yup this involves backend too! So a little learning is there...

**Comment by Doraemon012** [comment]
@Priyansh61 Sir, I would like to work on this issue. Please assign this to me.
First, I will get user's UID. Then, from all the data, I will filter user's data (on the basis of UID). Then, I will add delete button in every post of the user. The button will have a specific id. I will create a Delete function which will be triggered on clicking the delete button. The function will check the index of the PR clicked, and it will delete the selected PR.

**Comment by Priyansh61** [comment]
@Doraemon012 @anshikkay Both of you guys are showing interest on this PR, I guess one can handle the frontend and one backend, and you guys can work collabratively on this PR. One more thing I will be happy to teach you guys how to proceed with your implementation.

**Comment by Doraemon012** [comment]
Sir, if possible, I would like to work on this issue individually. I can handle the frontend too by myself. Please assign this to me.

**Comment by Priyansh61** [comment]
@Doraemon012 Since there is no response from @anshikkay Go ahead and lemme know if you need any help :)

**Comment by Priyansh61** [comment]
@Doraemon012 Updates?

**Comment by Doraemon012** [comment]
@Priyansh61 I will complete this by today.
