### ISSUE TITLE
[Feature Request]: to include  busify-android on the project section on bsoc website

### ISSUE THREAD

**Issue by abansal15** [bsoc-bitbyte/BSoC-Website#49]
### Is your feature request related to a problem? Please describe.

there is no section for  busify-android in the project section

### Describe the solution you'd like

i will add the  busify-android to the project section

**Comment by abansal15** [comment]
@Priyansh61 please assign this issue to me i will add this to project section

**Comment by abansal15** [comment]
@Priyansh61 raised the pr please look at it

**Comment by abansal15** [comment]
the above pr was made by mistake please assign this issue to me

**Comment by Priyansh61** [comment]
@abansal15 Go ahead, just ask @PraneGIT about the description to be included in the PR.

**Comment by abansal15** [comment]
@Priyansh61 raised the pr please review it
