### ISSUE TITLE
[BUG]: Navbar menu items not aligned properly

### ISSUE THREAD

**Issue by Doraemon012** [bsoc-bitbyte/BSoC-Website#57]
### Describe the bug

After clicking the ```MyPR's``` section, the ```Dashboard``` button gets displaced and is not aligned properly.

### Expected Behavior

The items in the navbar should be aligned properly, in a straight line.

### Screenshots/Videos

<img width="960" alt="NAV" src="https://github.com/bsoc-bitbyte/BSoC-Website/assets/116624667/2a250d11-47e9-4d7a-91c1-6374eee71aa4">

## Video:

https://github.com/bsoc-bitbyte/BSoC-Website/assets/116624667/34707477-9add-4008-aed5-eeba86d834d7

### What device are you using?

Desktop

**Comment by AkashPaloju** [comment]
@Priyansh61 I would like to work on this issue can u please assign it to me. I will make them to get aligned properly

**Comment by Priyansh61** [comment]
@AkashPaloju Go ahead!
