### ISSUE TITLE
[BUG]: Dashboard page not opening

### ISSUE THREAD

**Issue by Doraemon012** [bsoc-bitbyte/BSoC-Website#59]
### Describe the bug

Dashboard page in the **BSoC Website** is not opening. 

### Expected Behavior

The Dashboard page should open and display the user data.

### What device are you using?

Desktop, Mobile

**Comment by Doraemon012** [comment]
@Priyansh61 Sir, please assign this to me.
I have diagnosed the reason and I think can fix this.

**Comment by Priyansh61** [comment]
@Doraemon012 Fix it asap... Thanks!
