### ISSUE TITLE
[Feature Request]: Change the font size of title in the projects page

### ISSUE THREAD

**Issue by ramG-reddy** [bsoc-bitbyte/BSoC-Website#65]
### Is your feature request related to a problem? Please describe.

The current font size of the title is too small on mobile devices.

### Describe the solution you'd like

Make the font a little bigger only for mobile devices.

**Comment by ritankarsaha** [comment]
I would like to work on this issue. Please assign me this issue. I intend on making the current font size of the title responsive according to differenet devices making sure it doesn't look too small on mobile devices using sufficient media queries.
Thank You.

**Comment by ramG-reddy** [comment]
@ritankarsaha Go ahead 👍

**Comment by ritankarsaha** [comment]
@ramG-reddy I have resolved this issue #65 and also opened a PR for the same #68 .

Thank You.
