### ISSUE TITLE
[Feature Request]: Dynamically fetch the PRs in the submit PR page

### ISSUE THREAD

**Issue by rohansen856** [bsoc-bitbyte/BSoC-Website#66]
### Is your feature request related to a problem? Please describe.

Currently the user has to manually enter the details of their commit and submit it from the submit PR page.

### Describe the solution you'd like

I want to use the github api to fetch all the closed and merged pull requests from the repos instead of manually entering the details. 
It will not only increase the ease of access of the user, but also make the process of submitting PR more secure.
I will extract its difficulty level from the labels and use the BSoc'24 tag to filter valid PRs of this year.

### Describe alternatives you've considered

Please assign me this issue. I want to work on it.

**Comment by ramG-reddy** [comment]
@rohansen856 You may proceed!

**Comment by rohansen856** [comment]
@ramG-reddy  i have solved this issue and made a pull request #73. thank you.
