### ISSUE TITLE
[BUG]: Implement Error Handling in login/signup forms

### ISSUE THREAD

**Issue by ramG-reddy** [bsoc-bitbyte/BSoC-Website#70]
### Describe the bug

When I was testing the login and signup functionalities, I came across a situation when I was hitting the signup button and nothing is happening. I opened the console to find out the problem, it was just an error saying that I have already used this account to login. Also user has no way of knowing if an error occurs during a login.

### Steps To Reproduce

For Signup error: Make a google login with an account, try to signup using the same account.
edit: sign up using credentials with same account
For login error: Signup through credentials and type incorrect password in login.

### Expected Behavior

I expect a toast or banner or some other way of showing the user that "this" is the problem to abort the login/signup. Since regular users don't have the habit of opening consoles for errors.

Elaborate your implementation approach when requesting for assignment.

**Comment by sarthakChauhan12** [comment]
Is this issue resolved? If not I'd like to work on it.
