### ISSUE TITLE
[Feature Request]: Correct the behavior of Accordions in the home page

### ISSUE THREAD

**Issue by ramG-reddy** [bsoc-bitbyte/BSoC-Website#71]
### Is your feature request related to a problem? Please describe.

The accordion items in the home page are initially closed when the page loads, when you open one they expand and can't be closed which gives an odd experience to the user. They are hard coded using repetitive code and solely use html properties to get the current behavior, which is not ideal for updating the FAQs.

### Describe the solution you'd like

Implement a solution similar to the ones in projects page by making an FAQs array in the script tag, keeping the UI and functionality exactly the same. Make smooth animations for opening and closing of the accordions.

**Comment by ANIRUDHNARANG0** [comment]
@ramG-reddy  can i work on this issue , i will make the desirable changes ?

**Comment by ramG-reddy** [comment]
@ANIRUDHNARANG0 could you give an update about your progress

**Comment by ANIRUDHNARANG0** [comment]
Almost done will commit tonight
