### ISSUE TITLE
[Feature Request]: Count down in Home Page

### ISSUE THREAD

**Issue by ramG-reddy** [bsoc-bitbyte/BSoC-Website#76]
### Is your feature request related to a problem? Please describe.

It is important for the contributors to have an idea of the time left to contribute.

### Describe the solution you'd like

Implement count down feature under FAQs section with a font that fits in with the theme.

**Comment by tanishkaa08** [comment]
I would like to work on this issue. The first approach would be to create a date object in javascript representing the enddate and time. Next I would subtract the enddate from the current datee to display the remaining time and would also convert it to more user friendly format. I would then use the setinterval() function to update the timer continously till the enddate.
Thankyou.

**Comment by ramG-reddy** [comment]
Well, i would like to take in some more responses for approaches and assign the best one

**Comment by ShashaankS** [comment]
I would like to work on this issue. My approach will be to create a new section named as "Event end in" something like that under the Faq section, this section will contain the coundown logic using  setInterval() and Date.time() function, and displaying that in the form of " XX Days XX Hours XX Mins XX Secs left " and updating the the countdown element every second rounding off the millisecond. Hope this approach will fulfil the issue.

Thank You

**Comment by ramG-reddy** [comment]
I find @ritankarsaha's approach to be detailed and better to implement.

**Comment by ramG-reddy** [comment]
@ritankarsaha you may work on it now, make sure to also style it accordingly so that it fits well in the UI of the Home Page
