### ISSUE TITLE
Filter out results with zero score in the leaderboard/dashboard

### ISSUE THREAD

**Issue by ramG-reddy** [bsoc-bitbyte/BSoC-Website#77]
### Is your feature request related to a problem? Please describe.

It is not appropriate to have people with zero score in the dashboard

### Describe the solution you'd like

Dashboard should only display the names of contributors with score greater than zero

**Comment by Vaibhavsahu2810** [comment]
@ramG-reddy I would like to work on this issue.To solve this issue i will create a filter function or if-else relationship in vue.

**Comment by ShashaankS** [comment]
@ramG-reddy I am new to vue but i would like to work on  the issue and issue can be resolved using  some conditional statements

**Comment by yashpatil641** [comment]
@ramG-reddy i will make changes in the getcollection.js file and add conditional statement such that when we are getting data from firebase, docs with zero score will not be added in the documents array (doc.data().score>0)

**Comment by ramG-reddy** [comment]
> @ramG-reddy i will make changes in the getcollection.js file and add conditional statement such that when we are getting data from firebase, I will use firestore queries to exclude docs with zero score.
@yashpatil641 i wouldn't recommend changing the functions in the composables because they are probably reused in other places too..

using the v-if is not a great practice even though it does the job, because under the hood it conditionally injects html into tthe DOM which is not ideal. So I expect you to use the filter method itself to "filter out" (as mentioned in the title of the issue) the docs in js itself.

**Comment by yashpatil641** [comment]
> > @ramG-reddy i will make changes in the getcollection.js file and add conditional statement such that when we are getting data from firebase, I will use firestore queries to exclude docs with zero score.
> > @yashpatil641 i wouldn't recommend changing the functions in the composables because they are probably reused in other places too..
> 
> using the v-if is not a great practice even though it does the job, because under the hood it conditionally injects html into tthe DOM which is not ideal. So I expect you to use the filter method itself to "filter out" (as mentioned in the title of the issue) the docs in js itself.

@ramG-reddy in that case i can use filter function on documents array in script of dashboard.vue to resolve the issue

**Comment by rohansen856** [comment]
@ramG-reddy i would like to approach a little bit different method... i will modify the `getAllUserStats` function to filter out the scores here:
```js
            snap.docs.forEach((doc) => {
                if (doc.data().displayName != null && doc.data().uid != null) {
                    results.push({
                        ...doc.data(),
                        id: doc.id,
                        time_sec: doc.time,
                    })
                }
            })
so that i don't have to do any filtering in the frontend part itself. it will be independedent of the frontend logic,

**Comment by Vaibhavsahu2810** [comment]
@ramG-reddy earlier in my initial comment i commented one of the approach to create a filter function in the script of dashboard.vue to filter the users with score 0

**Comment by yashpatil641** [comment]
@ramG-reddy can I work on this issue ?

**Comment by ramG-reddy** [comment]
There is some maintenance that has to be done to the repo, after I'm done with it, I will start assigning issues again. It won't take more than 2 days, so please be patient.

**Comment by ramG-reddy** [comment]
@yashpatil641 you may work on the issue now, make sure to sync your branch before starting to work!
