### ISSUE TITLE
[Feature Request]: Modify the UI of myPR's page

### ISSUE THREAD

**Issue by Kaarti22** [bsoc-bitbyte/BSoC-Website#83]
### Is your feature request related to a problem? Please describe.

When a user hasn't submitted any PR's till now and opens the My PR's page, the table headings are shown but of no content, since he has no PR's submitted. This doesn't look good for a user who is ready to contribute for the first time.

### Describe the solution you'd like

Manage and show the loading states until the details of user's PR's are fetched. If he has no PR's, display some instructions of how to contribute to see his stats. Otherwise, display all his PR's in a table as usual.

**Comment by tanishkaa08** [comment]
I can work on this.

**Comment by ramG-reddy** [comment]
You could proceed now

**Comment by tanishkaa08** [comment]
@ramG-reddy could you provide with the specific instructions to display if someone has no PR's.

**Comment by Kaarti22** [comment]
![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/129477209/94d24bff-8c60-4302-9cd0-8b7fa4aaca35)

This is an example page design to display if there are no required items to display. Come with a similar idea to show if someone has no PR's. Select a suitable picture, description if any and implement it.

**Comment by Kaarti22** [comment]
@tanishkaa08 You also need to manage the loading states. When the user opens this page, it initially takes time to fetch his PR's. Then we generally check whether he has some PR's or not. So, the time until these details are fetched is a loading state.

Here is an example view of how to manage these states. 
![image](https://github.com/bsoc-bitbyte/BSoC-Website/assets/129477209/a4b2d1a4-96fa-41f8-90f2-a3501d6f88af)

So, we should display these first initially until we decide what to show, an empty PR's page or list of the PR's and then display appropriate views. Hence, come up with a solution to manage these kind of things efficiently.

**Comment by Kaarti22** [comment]
@tanishkaa08 Just now, I have submitted a PR and I can see myself in the dashboard section. But when I come back to myPR's page, still it's saying that I do not have any PR's. Try doing this and check whether the problem exists. If problem exists, debug and find out what's the mistake.

**Comment by tanishkaa08** [comment]
Uploading bsoc.mp4…

**Comment by Kaarti22** [comment]
The issue has been solved... Well done @tanishkaa08
