### ISSUE TITLE
[Feature Request]: Add pagination in the dashboard page

### ISSUE THREAD

**Issue by Kaarti22** [bsoc-bitbyte/BSoC-Website#93]
### Is your feature request related to a problem? Please describe.

The present dashboard page contains the list of contributors sorted in the highest number of points earned. But to see the whole list, user has to scroll all the way down which is not feasible if the list has a large number of entries.

### Describe the solution you'd like

Implement a paginated view in the dashboard page. There must be fixed number of entries in the table (for example. 10) and the remaining should be in the upcoming pages. Provide page numbers at the bottom. User should be able to navigate to any page at any moment. Also, provide previous and next buttons.

**Comment by yashpatil641** [comment]
I would like to work on this issue i will be making changes in the Dashboard.vue file.

**Comment by Kaarti22** [comment]
you could work on this issue now...
